// <auto-generated />
using FMS.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FMS.Core.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171104101007_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FMS.Core.Model.BillPayable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Amount");

                    b.Property<string>("BillNumber");

                    b.Property<string>("Description");

                    b.Property<string>("Economic");

                    b.Property<string>("Function");

                    b.Property<string>("Fund");

                    b.Property<string>("GeoCode");

                    b.Property<string>("Organisation");

                    b.Property<string>("PayerId");

                    b.Property<string>("Quantity");

                    b.Property<string>("Rate");

                    b.Property<string>("TransactionDate");

                    b.HasKey("Id");

                    b.ToTable("BillPayables");
                });

            modelBuilder.Entity("FMS.Core.Model.BillReceivable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Amount");

                    b.Property<string>("BillNumber");

                    b.Property<string>("Description");

                    b.Property<string>("Economic");

                    b.Property<string>("Function");

                    b.Property<string>("Fund");

                    b.Property<string>("GeoCode");

                    b.Property<string>("Organisation");

                    b.Property<string>("PayeeId");

                    b.Property<string>("Quantity");

                    b.Property<string>("Rate");

                    b.Property<string>("TransactionDate");

                    b.HasKey("Id");

                    b.ToTable("BillReceivable");
                });
#pragma warning restore 612, 618
        }
    }
}
